server:
  port: 8020

dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  cloud:
    subscribed-services: mloine-privoder

spring:
  application:
    # Dubbo 应用名称
    name: mloine-client
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      # 取消延迟加载
      eager: true

# actuator 相关辅助配置
management:
  endpoints:
    web:
      exposure:
        include: '*'

