server:
  port: 8010

spring:
  application:
    name: mloine-privoder
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      # 取消延迟加载
      eager: true

dubbo:
  scan:
    base-packages: com.mloine.alibaba.provider.service.impl
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost

